EdulabProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from EdulabProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('courses/', include('course.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from account import views

app_name = 'account'

urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('submit/', views.SubmitPageView.as_view(), name='submit'),
    path('logout/', views.LogoutUserView.as_view(), name='logout')
]

course/urls.py
from django.urls import path
from course import views

app_name = 'course'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='course_list'),
    path('<str:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<str:slug>/<int:pk>/', views.LoadSessionView.as_view(), name='load_session'),
    path('<str:slug>/add-comment/', views.add_comment, name='add_comment'),
    path('<str:slug>/comment-list/', views.comment_list, name='comment_list'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='main'),
]

templates/includes/footer.html
{% load static %}

<div id="dropDownSelect1"></div>
<div class="footer section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6 col-xs-12">
                <div class="single_footer">
                    <a href="index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    <p>لورم ایوم متن ساختگی با تولید آسان نامفهوم از صنعت چاپ با استفاده از طراحان گرافیک است.
                        چاپگرها و</p>
                    <div class="social_profile">
                        <ul>
                            <li><a href="#" class="f_facebook"><i class="ti-facebook" title="Facebook"></i></a></li>
                            <li><a href="#" class="f_twitter"><i class="ti-twitter" title="Twitter"></i></a></li>
                            <li><a href="#" class="f_instagram"><i class="ti-instagram" title="Instagram"></i></a>
                            </li>
                            <li><a href="#" class="f_linkedin"><i class="ti-linkedin" title="LinkedIn"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-sm-6 col-xs-12">
                <div class="single_footer">
                    <h4>درباره ادولب</h4>
                    <ul>
                        <li><a href="#">درباره ما</a></li>
                        <li><a href="#">ثبت نام مدرس</a></li>
                        <li><a href="#">معلم شدن</a></li>
                        <li><a href="#">همه مربیان</a></li>
                        <li><a href="#">سوال پرسیده شده</a></li>
                        <li><a href="#">با ما تماس بگیرید</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-sm-6 col-xs-12">
                <div class="single_footer">
                    <h4>دوره محبوب</h4>
                    <ul>
                        <li><a href="#">توسعه</a></li>
                        <li><a href="#">هنر و طراحی</a></li>
                        <li><a href="#">طراحی بصری</a></li>
                        <li><a href="#">طراحی گرافیک</a></li>
                        <li><a href="#">بازرسی کد</a></li>
                        <li><a href="#">بازاریابی دیجیتال</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-xs-12">
                <div class="single_footer">
                    <h4>اطلاعات تماس</h4>
                    <div class="sf_contact">
                        <span class="ti-map"></span>
                        <p>2570 کوادرا خیابان ویکتوریا، نیویورک، کانادا</p>
                    </div>
                    <div class="sf_contact">
                        <span class="ti-mobile"></span>
                        <p>+88 457 845 695</p>
                    </div>
                    <div class="sf_contact">
                        <span class="ti-mobile"></span>
                        <p><a href="tel:+88457845695">تماس با واتساپ</a></p>
                    </div>
                    <div class="sf_contact">
                        <span class="ti-email"></span>
                        <p>example@yourmail.com</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-sm-6 col-xs-12">
                <div class="single_footer">
                    <h4>دانلود برنامه</h4>
                    <p>برنامه ما را از فروشگاه برنامه و فروشگاه goole play دانلود کنید.</p>
                    <a href="index.html"><img src="{% static 'img/google-play.jpg' %}" class="foot_img" alt=""></a><a
                        href="index.html"><img src="{% static 'img/app-store.jpg' %}" class="foot_img" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="foot_copy">
    <div class="footer_copyright">
        <p>© 2024. All Rights Reserved.</p>
    </div>
</div>    

templates/includes/footer_refrences.html
{% load static %}

    <!--===============================================================================================-->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-simple-mobilemenu.js' %}"></script>
    <script src="{% static 'owlcarousel/js/owl_carousel.js' %}"></script>
    <script src="{% static 'owlcarousel/js/owl_carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.inview.min.js' %}"></script>
    <script src="{% static 'js/scrolltopcontrol.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/js-ajax.js' %}"></script>

</body>

</html>

templates/includes/head_refrences.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Eduleb - Education HTML Template">
    <meta name="keywords"
        content="agency, business, corporate, creative, html5, modern, multipurpose, One Page, parallax, startup">
    <title>Eduleb - آموزش برنامه نویسی</title>
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'img/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--===============================================================================================-->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/favicons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link
            href="https://fonts.googleapis.com/css2?family=Inria+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
            rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'owlcarousel/css/owl_carousel.css' %}">
    <link rel="stylesheet" href="{% static 'owlcarousel/css/owl_theme.css' %}">
    <link rel="stylesheet" href="{% static 'owlcarousel/css/owl_transitions.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-simple-mobilemenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="assets/img/favicons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
            href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100;9..40,200;9..40,300;9..40,400;9..40,500;9..40,600;9..40,700&family=Lexend:wght@300;400;500;600;700;800;900&family=Lobster&display=swap"
            rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

templates/includes/header.html
{% load static %}

<body data-spy="scroll" data-offset="80" onload="ScrollToTarget">
<div class="preloaders"><span class="loader"></span></div>
<div id="navigation" class="navbar-light bg-faded site-navigation">
    <div class="container-fluid">
        <div class="row">
            <div class="col-20 align-self-center">
                <div class="site-logo"><a href="index.html"><img src="{% static 'img/logo.png' %}" alt=""></a></div>
            </div>
            <div class="col-60 d-flex">
                <nav id="main-menu">
                    <ul>
                        <li>
                            <a href="{% url 'home:main' %}">صفحه اصلی</a>
                        </li>
                        <li><a href="about.html">در باره ما</a></li>
                        <li class="menu-item-has-children">
                            <a href="{% url 'course:course_list' %}">دوره ها</a>
                            <ul>
                                <li><a href="course.html">برنامه نویسی</a></li>
                                <li><a href="course_details.html">UI / UX</a></li>
                                <li><a href="course_details.html">وردپرس</a></li>
                                <li><a href="course_details.html">سئو</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">مدرسین</a>
                        </li>
                        <li>
                            <a href="blog.html">وبلاگ</a>
                        </li>
                    </ul>

                </nav>
            </div>

            <div class="col-20 d-none d-xl-block text-end align-self-center">
                <a href="contact.html" class="simple-icon" style="margin-left: 40px;"><i
                        class="fa-regular fa-cart-shopping"></i></a>
                {% if not request.user.is_authenticated %}
                    <a href="{% url 'account:login' %}" class="header-btn">ورود</a>
                    <a href="{% url 'account:submit' %}" class="btn_one">ثبت نام</a>
                {% else %}

                    <div id="main-menu" style="display: inline-block; margin-right: -40px">
                        <ul>
                            <li class="menu-item-has-children" id="user-full-name">
                                {% if request.user.first_name and request.user.last_name %}
                                    <a style="text-transform: none">{{ request.user.get_full_name }}</a>
                                {% else %}
                                    <a>{{ request.user.phone }}</a>
                                {% endif %}    
                                <ul>
                                    <li><a href="course.html">حساب کاربری</a></li>
                                    <li><a href="{% url 'account:logout' %}">خروج</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    {% if request.user.image %}
                        <img src="{{ request.user.image.url }}"
                             style="width: 30px; height: 30px; border-radius: 50px; margin-bottom: 5px; margin-left: -15px">
                    {% else %}
                        <img src="{% static 'img/profile.png' %}"
                             style="width: 30px; height: 30px; border-radius: 50px; margin-bottom: 5px">
                    {% endif %}
                {% endif %}
            </div>

            <ul class="mobile_menu">
                <li>
                    <a href="#">صفحه اصلی</a>
                    <ul class="sub-menu">
                        <li><a href="index.html">صفحه اصلی 01</a></li>
                        <li><a href="index2.html">صفحه اصلی 02</a></li>
                    </ul>
                </li>
                <li><a href="about.html">در باره</a></li>
                <li>
                    <a href="#">دوره</a>
                    <ul class="sub-menu">
                        <li><a href="course.html">دوره</a></li>
                        <li><a href="course_details.html">جزئیات دوره</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">صفحات</a>
                    <ul class="sub-menu">
                        <li><a href="instructor.html">مربی</a></li>
                        <li><a href="ins_details.html">مشخصات مربی</a></li>
                        <li><a href="pricing.html">طرح قیمت گذاری</a></li>
                        <li><a href="faq.html">صفحه فک</a></li>
                        <li><a href="404.html">404</a></li>
                    </ul>
                </li>
                <li>
                    <a href="blog.html">وبلاگ</a>
                    <ul class="sub-menu">
                        <li><a href="blog.html">وبلاگ</a></li>
                        <li><a href="blog_single.html">جزئیات وبلاگ</a></li>
                    </ul>
                </li>
                <li><a href="contact.html">مخاطب</a></li>
            </ul>
        </div>
    </div>
</div>